version: '3.9'

services:
  fastapi:
    build:
      context: .  # Contexto ajustado a la raíz del proyecto
      dockerfile: ./clinica_api/Dockerfile  # Dockerfile dentro de clinica_api
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    volumes:
      - ./clinica/clinica_db.sqlite:/app/clinica/clinica_db.sqlite
      - ./clinica/data:/app/clinica/data
    environment:
      - PYTHONPATH=/app

  streamlit:
      build:
        context: .
        dockerfile: ./streamlit/Dockerfile.streamlit
      container_name: streamlit
      ports:
        - "8501:8501"
      networks:
        - deploy_network
      volumes:
        - ./clinica:/app/clinica
        - ./main.py:/app/main.py
        - ./.streamlit:/app/.streamlit  # Añadir esta línea
      environment:
        - PYTHONPATH=/usr/local/lib/python3.10/site-packages
        - STREAMLIT_THEME_BASE=light
        - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

  web:
      build:
        context: .
      container_name: clinica_web
      ports:
        - "8001:8001"
      volumes:
        - ./clinica:/app/clinica
        - ./server.py:/app/server.py
      environment:
        - PYTHONPATH=/app
      command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001", "--reload"] 

networks:
  deploy_network:
    driver: bridge
