version: '3.8'

services:
  fastapi:
    build: fastapi/
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    container_name: fastapi
    volumes:
      - mis_datos:/var/lib/docker/volumes/aa-streamlit-fastapi_mis_datos/_data

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
      - mis_datos:/var/lib/docker/volumes/aa-streamlit-fastapi_mis_datos/_data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinica_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./clinica.db
    command: ["python3", "clinica/main.py"]

networks:
  deploy_network:
    driver: bridge

volumes:
  mis_datos:

