services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    container_name: fastapi
    volumes:
      - .:/app

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile  
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
      - .:/app
    command: >
      /bin/sh -c "python init_db.py && streamlit run main.py"


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinica_web
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./clinica.db
    command: ["python3", "clinica/main.py"]

networks:
  deploy_network:
    driver: bridge
