services:
  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    volumes:
      - ./clinica_db.sqlite:/app/clinica_db.sqlite  # Volumen compartido
    environment:
      - PYTHONPATH=/app
    command: ["python3", "clinica/database.py"]

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    volumes:
      - ./clinica_db.sqlite:/app/clinica_db.sqlite  # Volumen compartido
    environment:
      - PYTHONPATH=/app
    command: >
      /bin/sh -c "python clinica/database.py && streamlit run main.py"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinica_web
    ports:
      - "8001:8001"
    volumes:
      - ./clinica_db.sqlite:/app/clinica_db.sqlite  # Volumen compartido
    environment:
      - PYTHONPATH=/app
    command: ["python3", "clinica/database.py"]

networks:
  deploy_network:
    driver: bridge
